package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/MakFly/vx/pkg/engine"
)

// GenerateMarkdown produces a markdown report suitable for PR comments

func GenerateMarkdown(result engine.ScoreResult, target string, delta *int) string {
	var sb strings.Builder

	// Header
	sb.WriteString("## VX Security Report\n\n")

	// Score with optional delta
	gradeEmoji := gradeToEmoji(result.Grade)
	sb.WriteString(fmt.Sprintf("**Score: %d/100** %s **Grade: %s**", result.Score, gradeEmoji, result.Grade))
	if delta != nil {
		if *delta > 0 {
			sb.WriteString(fmt.Sprintf(" *(+%d vs base)*", *delta))
		} else if *delta < 0 {
			sb.WriteString(fmt.Sprintf(" *(%d vs base)*", *delta))
		} else {
			sb.WriteString(" *(no change vs base)*")
		}
	}
	sb.WriteString("\n\n")

	// Target
	sb.WriteString(fmt.Sprintf("**Target:** `%s`\n\n", target))

	// Summary table
	sb.WriteString("| Severity | Count |\n|----------|-------|\n")
	for _, sev := range []engine.Severity{engine.SevCritical, engine.SevHigh, engine.SevMedium, engine.SevLow, engine.SevInfo} {
		count := result.Summary[sev]
		sb.WriteString(fmt.Sprintf("| %s %s | %d |\n", sevEmoji(sev), sev, count))
	}
	sb.WriteString("\n")

	// Top findings (critical + high only for PR brevity)
	sort.Slice(result.Findings, func(i, j int) bool {
		return result.Findings[i].Severity > result.Findings[j].Severity
	})

	var topFindings []engine.Finding
	for _, f := range result.Findings {
		if f.Severity >= engine.SevMedium {
			topFindings = append(topFindings, f)
		}
	}

	if len(topFindings) > 0 {
		sb.WriteString("<details>\n<summary>Top findings</summary>\n\n")
		for _, f := range topFindings {
			sb.WriteString(fmt.Sprintf("- **[%s]** %s — %s\n", f.Severity, f.Title, f.Description))
			if f.Remediation != "" {
				sb.WriteString(fmt.Sprintf("  - Fix: %s\n", f.Remediation))
			}
		}
		sb.WriteString("\n</details>\n\n")
	}

	sb.WriteString("---\n*Generated by [VX Security Scanner](https://github.com/MakFly/vx)*\n")

	return sb.String()
}

func gradeToEmoji(g engine.Grade) string {
	switch g {
	case engine.GradeA:
		return "🟢"
	case engine.GradeB:
		return "🟢"
	case engine.GradeC:
		return "🟡"
	case engine.GradeD:
		return "🟠"
	case engine.GradeF:
		return "🔴"
	}
	return "⚪"
}

func sevEmoji(s engine.Severity) string {
	switch s {
	case engine.SevCritical:
		return "🔴"
	case engine.SevHigh:
		return "🟠"
	case engine.SevMedium:
		return "🟡"
	case engine.SevLow:
		return "🔵"
	case engine.SevInfo:
		return "⚪"
	}
	return ""
}
